/**
 * Writes src/catalog/generated.ts from what extract.mjs actually produced.
 *
 *   node tools/gen-catalog.mjs
 *
 * Sizes, anchors and frame openings are facts about the assets on disk, so they
 * are read off the assets rather than retyped. Names and prices are editorial
 * and live in this file's tables — until the admin owns them (SPEC §7).
 */
import fs from 'node:fs';
import path from 'node:path';
import { OUT_DIR, CANON, SOURCES } from './sources.mjs';
import { BASE_SCALE } from './passes.mjs';

const OUT = 'd:/laragon/www/door configurator/kiosk/src/catalog/generated.ts';

const DOOR_NAME = {
  hexagon: { uz: 'Olti burchak', kk: 'Altı múyesh', ru: 'Шестигранник' },
  lattice: { uz: 'Panjara', kk: 'Pánjara', ru: 'Решётка' },
  classic: { uz: 'Klassik panel', kk: 'Klassik panel', ru: 'Классическая филёнка' },
  twopanel: { uz: 'Ikki panel', kk: 'Eki panel', ru: 'Две филёнки' },
  flush: { uz: 'Zamonaviy tekis', kk: 'Zamanagóy tegis', ru: 'Современная гладкая' },
};

const FRAME_NAME = {
  flat: { uz: 'Tekis', kk: 'Tegis', ru: 'Плоский' },
  fluted: { uz: 'Qirrali', kk: 'Qırlı', ru: 'Каннелюрный' },
  reeded: { uz: 'Chiziqli', kk: 'Sızıqlı', ru: 'Рифлёный' },
  plinth: { uz: 'Poydevorli', kk: 'Tiykarlı', ru: 'С цоколем' },
};

const BASE_PRICE = {
  hexagon: 4_200_000,
  lattice: 3_900_000,
  classic: 3_200_000,
  twopanel: 3_400_000,
  flush: 2_800_000,
};

const FRAME_PRICE = { flat: 0, fluted: 450_000, reeded: 350_000, plinth: 600_000 };

const SKU = {
  hexagon: 'DK-HEX-01',
  lattice: 'DK-LAT-01',
  classic: 'DK-CLS-01',
  twopanel: 'DK-2PN-01',
  flush: 'DK-FLS-01',
};

const metas = SOURCES.map((s) =>
  JSON.parse(fs.readFileSync(path.join(OUT_DIR, s.id, 'meta.json'), 'utf8'))
);

/** One frame per distinct style, taken from the model it was photographed on. */
const frames = [];
for (const m of metas) {
  if (frames.some((f) => f.style === m.frameStyle)) continue;
  frames.push({ id: m.frameStyle, style: m.frameStyle, from: m.id, ...m.frame });
}

const p = (id, part) => ({
  base: `/assets/doors/${id}/${part}_base.png`,
  ao: `/assets/doors/${id}/${part}_ao.png`,
  spec: `/assets/doors/${id}/${part}_spec.png`,
  mask: `/assets/doors/${id}/${part}_mask.png`,
});

const doors = metas.map((m) => ({
  id: m.id,
  sku: SKU[m.id],
  name: DOOR_NAME[m.id],
  geometry: m.geometry,
  naqsh: m.naqsh,
  hinge: m.hinge,
  basePrice: BASE_PRICE[m.id],
  leaf: p(m.id, 'leaf'),
  hardware: m.hardware.map((h) => ({ ...h, file: `/assets/doors/${m.id}/${h.file}` })),
  allows: {
    // Every frame fits every leaf: the openings are normalised to CANON, so
    // pairing is geometric rather than editorial. When a real pair turns out to
    // be unbuildable, drop it from this list and the UI stops offering it.
    frames: frames.map((f) => f.id),
    // Nothing in the photographed set has a glazed panel yet. An empty list is
    // how SPEC §6 makes an invalid state unreachable — the glass tab does not
    // render at all rather than rendering and rejecting.
    glass: [],
  },
}));

const frameOut = frames.map((f) => ({
  id: f.id,
  name: FRAME_NAME[f.style],
  style: f.style,
  passes: p(f.from, 'frame'),
  width: f.width,
  height: f.height,
  inner: f.inner,
  priceDelta: FRAME_PRICE[f.style] ?? 0,
}));

const banner = `/**
 * GENERATED by tools/gen-catalog.mjs — do not edit.
 * Regenerate after tools/extract.mjs with:  node tools/gen-catalog.mjs
 */
import type { DoorModel, FrameModel } from './types';
`;

const body =
  banner +
  `\nexport const CANON = ${JSON.stringify(CANON)} as const;\n` +
  `
/**
 * The factor base_*.png was written down by, so it would fit in 8 bits. The
 * shader must scale it back or every door renders as though painted grey — which
 * looks plausible enough to ship, so the number crosses the pipeline/runtime
 * boundary here rather than being typed twice.
 */
export const BASE_SCALE = ${BASE_SCALE};
` +
  `\nexport const DOORS: DoorModel[] = ${JSON.stringify(doors, null, 2)};\n` +
  `\nexport const FRAMES: FrameModel[] = ${JSON.stringify(frameOut, null, 2)};\n`;

fs.writeFileSync(OUT, body);
console.log(`wrote ${OUT}`);
console.log(`  ${doors.length} doors, ${frameOut.length} frames (${frames.map((f) => f.style).join(', ')})`);
