// GENERATED by tools/leaves.mjs — do not edit by hand.
// Re-run: node tools/leaves.mjs
import type { Leaf } from './types';

export const LEAVES: Leaf[] = [
  {
    id: 'lattice',
    name: { uz: 'Romb naqsh', kk: 'Romb naqıs', ru: 'Ромб' },
    image: '/assets/leaves/lattice.png',
    /** measured, not assumed — see tools/leaves.mjs */
    aspect: 0.3939,
    handleSide: 'left',
    /** false when the leaf still wears the handle it was photographed with */
    handleSwappable: false,
    /** so the bench can reopen and re-cut this door — loaded only when editing */
    source: '/assets/leaves/lattice-src.jpg',
    corners: [{ x: 0.194, y: 0.1097 }, { x: 0.8163, y: 0.1134 }, { x: 0.7899, y: 0.972 }, { x: 0.2028, y: 0.9746 }],
    white: true,
    handleChoice: 'none',
  },
  {
    id: 'classic',
    name: { uz: 'Klassik panel', kk: 'Klassik panel', ru: 'Классическая' },
    image: '/assets/leaves/classic.png',
    /** measured, not assumed — see tools/leaves.mjs */
    aspect: 0.3972,
    handleSide: 'left',
    /** false when the leaf still wears the handle it was photographed with */
    handleSwappable: false,
    /** so the bench can reopen and re-cut this door — loaded only when editing */
    source: '/assets/leaves/classic-src.jpg',
    corners: [{ x: 0.1775, y: 0.088 }, { x: 0.8135, y: 0.0896 }, { x: 0.7945, y: 0.9673 }, { x: 0.1865, y: 0.9684 }],
    white: true,
    handleChoice: 'none',
  },
  {
    id: 'twopanel',
    name: { uz: 'Ikki panel', kk: 'Eki panel', ru: 'Две филёнки' },
    image: '/assets/leaves/twopanel.png',
    /** measured, not assumed — see tools/leaves.mjs */
    aspect: 0.3988,
    handleSide: 'left',
    /** false when the leaf still wears the handle it was photographed with */
    handleSwappable: false,
    /** so the bench can reopen and re-cut this door — loaded only when editing */
    source: '/assets/leaves/twopanel-src.jpg',
    corners: [{ x: 0.1901, y: 0.1067 }, { x: 0.8231, y: 0.1072 }, { x: 0.8064, y: 0.966 }, { x: 0.2141, y: 0.9726 }],
    white: true,
    handleChoice: 'none',
  },
  {
    id: 'rosette',
    name: { uz: 'Rozetka', kk: 'Rozetka', ru: 'Розетка' },
    image: '/assets/leaves/rosette.png',
    /** measured, not assumed — see tools/leaves.mjs */
    aspect: 0.3483,
    handleSide: 'right',
    /** false when the leaf still wears the handle it was photographed with */
    handleSwappable: false,
    /** so the bench can reopen and re-cut this door — loaded only when editing */
    source: '/assets/leaves/rosette-src.jpg',
    corners: [{ x: 0.2011, y: 0.0918 }, { x: 0.7502, y: 0.0941 }, { x: 0.7344, y: 0.9642 }, { x: 0.2027, y: 0.9633 }],
    white: true,
    handleChoice: 'none',
  },
];
